### ISSUE TITLE
[FEAT] French Language

### ISSUE THREAD

**Issue by nocturni** [Rodrogamby/telepotions#1]
Sorry about not putting this as a pull request, I do not know how to do pull requests on github.

Here's a pastebin to a french translation I made, it follows the french syntax of vanilla Minecraft and should be clear enough for players.

fr_fr.lang

https://pastebin.com/j7RpPTBz

**Comment by Rodrogamby** [comment]
Implemented! :)
d35ced9 & 3e3afd0
